name: Deploiement HTML Statique

on:
  push:
    branches: ["main"] # Se lance quand vous poussez sur la branche principale

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true' # On anticipe le changement de juin 2026
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v4

      - name: Téléchargement de l'artefact (votre HTML)
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Télécharge tout le contenu du dossier racine

      - name: Déploiement réel
        id: deployment
        uses: actions/deploy-pages@v4