name: Deploiement Portfolio

on:
  push:
    branches: ["main"] # Vérifiez que votre branche s'appelle bien main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # On force Node 24 pour supprimer l'alerte de dépréciation
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v5 # Version mise à jour

      - name: Creation de l'artefact (HTML seul)
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # On envoie tout le dossier racine

      - name: Deploiement reel
        id: deployment
        uses: actions/deploy-pages@v4